### ISSUE TITLE
Should entries that do the same thing have the same name?

### ISSUE THREAD

**Issue by PaulMansour** [abrudz/aplcart#19]
There are at least 4 entries for deleting leading blanks:

Drop Leading Blanks
Remove leading blanks
Fast: Dv without any leading blank spaces (2 of these)

Should these all be the same with exception of an optional  leading modifier like "fast"? 

Alternatively, should there be a link between identical entries? So if you find one, you know exactly how many alternatives there are?

**Comment by abrudz** [comment]
I'm undecided on removing equivalents (I remove true duplicates when I find them). I'll try to align their description when I spot them.

The idea is that the synonyms are sufficient to find all together. Addition of synonyms is of course a constant WIP.

I'm not sure how I could link entries without reworking the system (e.g. entries could have an equivalence tag so if one entry with that tag is shown, they all are) but this complicates an otherwise very simple system.
